
CREATE TABLE Users (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserName VARCHAR(50),
    Password VARCHAR(50),
    LastLogin TIMESTAMP,
    UserSettings JSONB
);

CREATE TABLE Sets (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    UserID BIGINT REFERENCES Users(ID),
    SetData JSONB,
    Modified TIMESTAMP
);